// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActivityQuery = { limit: number | null, };

export type ActivityResponse = { id: string, site_id: string, user_id: string, activity_type: string, content: string | null, photo_url: string | null, created_at: string, };

export type AssignUserRequest = { user_id: string, role: string | null, };

export type AssignmentResponse = { id: string, site_id: string, user_id: string, role: string, created_at: string, };

export type CreateActivityRequest = { activity_type: string, content: string | null, photo_url: string | null, };

export type CreateSiteRequest = { name: string, customer_name: string, location: string | null, description: string | null, start_date: string | null, end_date: string | null, estimated_days: number | null, };

export type CreateTimeEntryRequest = { site_id: string | null, work_type: string, hours: number, work_date: string, notes: string | null, };

export type DashboardSiteResponse = { id: string, name: string, customer_name: string, location: string | null, status: string, start_date: string | null, end_date: string | null, estimated_days: number | null, assigned_users: bigint, total_hours: number, };

export type ListSitesQuery = { status: string | null, };

export type SiteResponse = { id: string, name: string, customer_name: string, location: string | null, description: string | null, status: string, start_date: string | null, end_date: string | null, estimated_days: number | null, created_at: string, };

export type SiteStockHistoryResponse = { id: string, material_id: string, material_name: string, category_name: string, quantity_change: number, quantity_after: number, notes: string | null, site_id: string | null, site_name: string | null, extracted_by: string, created_at: string, };

export type TimeEntryResponse = { id: string, site_id: string | null, user_id: string, work_type: string, hours: number, work_date: string, notes: string | null, created_at: string, };

export type UpdateSiteRequest = { name: string | null, customer_name: string | null, location: string | null, description: string | null, status: string | null, start_date: string | null, end_date: string | null, estimated_days: number | null, };

export type UpdateTimeEntryRequest = { site_id: string | null, work_type: string | null, hours: number | null, work_date: string | null, notes: string | null, };

export type UploadPhotoAttachmentResponse = { attachment_id: string, photo_url: string, thumbnail_url: string, };
