// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActivityQuery = { limit: number | null, };

export type ActivityResponse = { id: string, site_id: string, user_id: string, creator_name: string, can_delete: boolean, activity_type: string, content: string | null, photo_url: string | null, attachments: Array<SiteActivityAttachmentResponse>, created_at: string, };

export type AdjustStockRequest = { quantity: number, reason: string, };

export type ApproveOrderRequestDto = { notes: string | null, };

export type AssignUserRequest = { user_id: string, role: string | null, };

export type AssignmentResponse = { id: string, site_id: string, user_id: string, role: string, created_at: string, };

export type AvailabilityQuery = { resource_type: string, resource_id: string, start_time: string, end_time: string, };

export type AvailabilityResponse = { available: boolean, conflicts: Array<ConflictDetail> | null, };

export type CalendarEntryResponse = { resource_type: string, resource_id: string, resource_name: string, resource_display_color: string | null, reservations: Array<ReservationSummaryResponse>, };

export type CalendarQuery = { start_date: string, end_date: string, resource_type: string | null, site_id: string | null, };

export type CalendarResponse = { resources: Array<CalendarEntryResponse>, };

export type CategoryResponse = { id: string, name: string, description: string | null, can_expire: boolean, created_at: string, };

export type ConflictDetail = { id: string, user_name: string | null, start_time: string, end_time: string, status: string, };

export type CreateActivityRequest = { activity_type: string, content: string | null, photo_url: string | null, attachment_ids: Array<string>, };

export type CreateCategoryRequest = { name: string, description: string | null, can_expire: boolean, };

export type CreateMachineRequest = { name: string, machine_type: string | null, description: string | null, location: string | null, qr_code: string | null, };

export type CreateMaintenanceScheduleRequest = { asset_id: string, task_description: string, interval_days: number, next_due_date: string, };

export type CreateMaintenanceScheduleResponse = { schedule: MaintenanceScheduleResponse, due: MaintenanceDueResponse, };

export type CreateMaterialRequest = { category_id: string, name: string, description: string | null, unit: string, quantity: number, min_quantity: number, location: string | null, expires_on: string | null, batch_code: string | null, };

export type CreateOnboardingSessionRequest = { organization_name: string, admin_email: string, admin_name: string | null, selected_plan: string, };

export type CreateOrderRequestDto = { material_id: string, quantity: number, reason: string | null, };

export type CreateProjectInvoiceRequest = { sender_name: string | null, sender_address: string | null, };

export type CreateReservationRequest = { resource_type: string, resource_id: string, site_id: string | null, project_id: string | null, start_time: string, end_time: string, purpose: string | null, notes: string | null, };

export type CreateSiteAppointmentRequest = { title: string, appointment_kind: string, starts_at: string, ends_at: string, notes: string | null, assigned_user_ids: Array<string>, };

export type CreateSiteRequest = { project_type: string, name: string, customer_name: string, location: string | null, description: string | null, start_date: string | null, end_date: string | null, estimated_days: number | null, budget_amount_cents: bigint | null, billing_reference: string | null, billing_notes: string | null, quote_reference: string | null, };

export type CreateTimeEntryRequest = { site_id: string | null, work_type: string, hours: number, work_date: string, notes: string | null, };

export type CreateToolRequest = { name: string, category: string | null, description: string | null, location: string | null, qr_code: string | null, };

export type CreateVehicleRequest = { name: string, license_plate: string | null, vehicle_type: string, description: string | null, location: string | null, qr_code: string | null, display_color: string | null, };

export type DashboardSiteResponse = { id: string, project_type: string, name: string, customer_name: string, location: string | null, status: string, start_date: string | null, end_date: string | null, estimated_days: number | null, assigned_users: bigint, total_hours: number, };

export type EnrichedStockHistoryResponse = { id: string, material_id: string, user_id: string, user_name: string, entry_type: EntryType, quantity_change: number, quantity_after: number, notes: string | null, site_id: string | null, site_name: string | null, category_name: string, created_at: string, };

/**
 * Entry type for stock history entries
 */
export type EntryType = "withdrawn" | "disposed" | "adjusted" | "material_added" | "location_changed" | "min_quantity_changed";

export type ExpiryBatchResponse = { id: string, batch_code: string | null, expires_on: string, quantity: number, received_at: string, is_expired: boolean, is_expiring_soon: boolean, };

export type FulfillOrderRequestDto = { actual_quantity: number, notes: string | null, };

/**
 * Request DTO for inviting a user
 */
export type InviteUserRequest = { email: string, name: string | null, role: string, };

export type InviteUserResponse = { id: string, email: string, role: string, status: string, invite_url: string, organization_alias: string, expires_at: string, };

export type InvoiceResponse = { id: string, site_id: string, invoice_number: bigint, invoice_number_display: string, status: string, sender_name: string | null, sender_address: string | null, issued_at: string | null, due_on: string | null, voided_at: string | null, pdf_artifact: PdfArtifactResponse | null, created_by: string | null, created_at: string, updated_at: string, };

export type ListMachinesQuery = { status: string | null, };

export type ListMaintenanceDueQuery = { asset_id: string | null, status: string | null, };

export type ListMaintenanceSchedulesQuery = { asset_id: string | null, };

export type ListMaterialsQuery = { category_id: string | null, };

export type ListReservationsQuery = { user_id: string | null, resource_type: string | null, resource_id: string | null, site_id: string | null, };

export type ListSitesQuery = { status: string | null, };

export type ListToolsQuery = { status: string | null, category: string | null, };

export type ListVehiclesQuery = { status: string | null, };

export type MachineResponse = { id: string, name: string, machine_type: string | null, description: string | null, status: string, location: string | null, qr_code: string | null, created_at: string, updated_at: string, };

export type MaintenanceDueResponse = { id: string, schedule_id: string, asset_id: string, resource_type: string, resource_name: string, task_description: string, due_date: string, status: string, severity: string, resolved_at: string | null, resolved_by: string | null, resolution_notes: string | null, created_at: string, updated_at: string, };

export type MaintenanceScheduleResponse = { id: string, asset_id: string, task_description: string, interval_days: number, is_active: boolean, created_at: string, updated_at: string, };

export type MarkOrderedRequestDto = { notes: string | null, };

export type MaterialResponse = { id: string, category_id: string, name: string, description: string | null, unit: string, quantity: number, min_quantity: number, can_expire: boolean, legacy_quantity: number, expired_quantity: number, expiring_soon_quantity: number, next_expiry_on: string | null, expiry_batches: Array<ExpiryBatchResponse>, location: string | null, qr_code: string | null, is_low_stock: boolean, created_at: string, };

export type MollieWebhookRequest = { id: string, };

export type MollieWebhookResponse = { status: string, payment_id: string, event_inserted: boolean, provider_status: string, session_status: string | null, };

export type OnboardingSessionResponse = { session_id: string, organization_slug: string, status: string, payment_provider: string | null, payment_id: string | null, checkout_url: string, };

export type OnboardingSessionStatusResponse = { session_id: string, organization_slug: string, status: string, error_message: string | null, };

export type OrderRequestResponse = { id: string, material_id: string, material_name: string, quantity: number, requested_by: string, status: string, request_kind: string, reason: string | null, approved_by: string | null, approved_at: string | null, fulfilled_at: string | null, notes: string | null, created_at: string, };

export type OrderStatusQuery = { status: string | null, };

export type PdfArtifactResponse = { storage_path: string, sha256_hash: string, content_type: string, size_bytes: bigint, created_at: string, };

/**
 * Response DTO for user preferences
 */
export type PreferencesResponse = { active_site_id: string | null, };

export type ProjectInvoiceDraftResponse = { invoice: InvoiceResponse, project: SiteInvoiceProjectResponse, billing: SiteInvoiceBillingResponse, labor: ProjectLaborSummaryResponse, materials: ProjectMaterialSummaryResponse, line_items: Array<ProjectInvoiceLineItemResponse>, };

export type ProjectInvoiceLineItemResponse = { source: string, description: string, quantity: number, unit: string, source_count: bigint, priced: boolean, };

export type ProjectLaborSummaryResponse = { total_hours: number, entry_count: bigint, site_hours: number, workshop_hours: number, last_work_date: string | null, };

export type ProjectMaterialSummaryResponse = { distinct_material_count: bigint, withdrawal_count: bigint, lines: Array<ProjectMaterialUsageLineResponse>, };

export type ProjectMaterialUsageLineResponse = { material_id: string, material_name: string, category_name: string, unit: string, total_withdrawn: number, withdrawal_count: bigint, last_withdrawn_at: string, };

export type PublicInviteResponse = { email: string, role: string, status: string, expires_at: string, };

export type QrCodeResponse = { qr_code: string, material_id: string, material_name: string, };

export type QrStatusResponse = { resource_type: string, resource_id: string, resource_name: string, status: string, current_reservation: ReservationSummaryResponse | null, upcoming_reservations: Array<ReservationSummaryResponse>, };

export type QrSvgResponse = { svg: string, qr_code: string, };

export type ReservationHolderResponse = { user_id: string, user_name: string | null, };

export type ReservationResponse = { id: string, resource_type: string, resource_id: string, resource_name: string, user_id: string, user_name: string | null, site_id: string | null, site_name: string | null, project_id: string | null, project_name: string | null, start_time: string, end_time: string, status: string, purpose: string | null, notes: string | null, current_holder: ReservationHolderResponse | null, created_at: string, updated_at: string, };

export type ReservationSummaryResponse = { id: string, start_time: string, end_time: string, user_name: string | null, site_id: string | null, site_name: string | null, status: string, };

export type ResolveMaintenanceDueRequest = { resolution_notes: string | null, };

export type SiteActivityAttachmentResponse = { attachment_id: string, filename: string, mime_type: string, url: string, thumbnail_url: string | null, };

export type SiteAppointmentResponse = { id: string, site_id: string, title: string, appointment_kind: string, starts_at: string, ends_at: string, notes: string | null, assigned_user_ids: Array<string>, created_at: string, updated_at: string, };

export type SiteAppointmentsQuery = { start_date: string | null, end_date: string | null, };

export type SiteHistoryReportQuery = { customer: string | null, project_type: string | null, worker_id: string | null, date_from: string | null, date_to: string | null, duration_min_hours: number | null, duration_max_hours: number | null, cost_basis: string | null, };

export type SiteHistoryReportRowResponse = { site_id: string, project_type: string, name: string, customer_name: string, status: string, start_date: string | null, end_date: string | null, estimated_days: number | null, budget_amount_cents: bigint | null, billing_reference: string | null, quote_reference: string | null, total_hours: number, worker_count: bigint, distinct_material_count: bigint, withdrawal_count: bigint, cost_basis: string, };

export type SiteInvoiceBillingResponse = { budget_amount_cents: bigint | null, quote_reference: string | null, billing_reference: string | null, billing_notes: string | null, };

export type SiteInvoiceProjectResponse = { id: string, name: string, project_type: string, customer_name: string, location: string | null, status: string, start_date: string | null, end_date: string | null, estimated_days: number | null, };

export type SiteInvoiceSummaryResponse = { export_version: string, generated_at: string, project: SiteInvoiceProjectResponse, billing: SiteInvoiceBillingResponse, labor: ProjectLaborSummaryResponse, materials: ProjectMaterialSummaryResponse, };

export type SiteProjectSummaryResponse = { labor: ProjectLaborSummaryResponse, materials: ProjectMaterialSummaryResponse, };

export type SiteResponse = { id: string, project_type: string, name: string, customer_name: string, location: string | null, description: string | null, status: string, start_date: string | null, end_date: string | null, estimated_days: number | null, budget_amount_cents: bigint | null, billing_reference: string | null, billing_notes: string | null, quote_reference: string | null, created_at: string, };

export type SiteStockHistoryResponse = { id: string, material_id: string, material_name: string, category_name: string, quantity_change: number, quantity_after: number, notes: string | null, site_id: string | null, site_name: string | null, extracted_by: string, created_at: string, };

/**
 * Response DTO for stock entry history
 */
export type StockEntryResponse = { id: string, quantity_change: number, quantity_after: number, notes: string | null, site_id: string | null, site_name: string | null, created_at: string, };

export type StockInRequest = { quantity: number, notes: string | null, expires_on: string | null, batch_code: string | null, supplier_name: string | null, receipt_reference: string | null, receipt_date: string | null, };

export type TimeEntryResponse = { id: string, site_id: string | null, user_id: string, creator_name: string, can_edit: boolean, can_delete: boolean, work_type: string, hours: number, work_date: string, notes: string | null, created_at: string, };

export type ToolResponse = { id: string, name: string, category: string | null, description: string | null, status: string, location: string | null, qr_code: string | null, created_at: string, updated_at: string, };

export type UpdateCategoryRequest = { name?: string, description?: string, can_expire?: boolean, };

export type UpdateMachineRequest = { name: string | null, machine_type: string | null, description: string | null, status: string | null, location: string | null, qr_code: string | null, };

export type UpdateMaterialRequest = { location?: string, min_quantity?: number, clear_location?: boolean, };

export type UpdatePreferences = { active_site_id: string | null, };

/**
 * Request DTO for updating preferences
 */
export type UpdatePreferencesRequest = { active_site_id: string | null, };

/**
 * Request DTO for updating profile
 */
export type UpdateProfileRequest = { name: string | null, };

export type UpdateReservationRequest = { start_time: string | null, end_time: string | null, site_id: string | null, project_id: string | null, purpose: string | null, notes: string | null, status: string | null, };

/**
 * Request DTO for updating role
 */
export type UpdateRoleRequest = { role: string, };

export type UpdateSiteAppointmentRequest = { title: string | null, appointment_kind: string | null, starts_at: string | null, ends_at: string | null, notes: string | null, clear_notes: boolean | null, assigned_user_ids: Array<string> | null, };

export type UpdateSiteRequest = { project_type: string | null, name: string | null, customer_name: string | null, location: string | null, description: string | null, status: string | null, start_date: string | null, end_date: string | null, estimated_days: number | null, budget_amount_cents: bigint | null, billing_reference: string | null, billing_notes: string | null, quote_reference: string | null, clear_budget_amount: boolean | null, clear_billing_reference: boolean | null, clear_billing_notes: boolean | null, clear_quote_reference: boolean | null, };

export type UpdateTimeEntryRequest = { site_id: string | null, work_type: string | null, hours: number | null, work_date: string | null, notes: string | null, };

export type UpdateToolRequest = { name: string | null, category: string | null, description: string | null, status: string | null, location: string | null, qr_code: string | null, };

export type UpdateVehicleRequest = { name: string | null, license_plate: string | null, vehicle_type: string | null, description: string | null, status: string | null, location: string | null, qr_code: string | null, display_color: string | null, };

export type UploadPhotoAttachmentResponse = { attachment_id: string, photo_url: string, thumbnail_url: string, };

export type UploadSiteAttachmentResponse = { attachment_id: string, filename: string, mime_type: string, url: string, thumbnail_url: string | null, };

export type UserPreferences = { active_site_id: string | null, };

/**
 * Response DTO for user data
 */
export type UserResponse = { id: string, email: string, name: string | null, role: string, created_at: string, };

export type VehicleResponse = { id: string, name: string, license_plate: string | null, vehicle_type: string, description: string | null, status: string, location: string | null, qr_code: string | null, display_color: string, created_at: string, updated_at: string, };

export type WithdrawRequest = { quantity: number, notes: string | null, site_id: string | null, disposal: boolean | null, last_package_taken: boolean | null, };
